### ISSUE TITLE
WebSocketOptions is not exposed

### ISSUE THREAD

**Issue by efraimbart** [sharpbitstudio/flutter-websocket-support-mobile-implementation#12]
Users of this package are unable to instantiate WebSocketOptions and supply it to a connection as it is not exposed in the package. See https://github.com/sharpbitstudio/flutter-websocket-support-mobile-implementation/blob/master/lib/web_socket_support.dart#L12.

For now, a workaround is to manually import it as below:
```dart
import 'package:web_socket_support_platform_interface/web_socket_options.dart';
```

**Comment by sharpbitstudio** [comment]
Fixed in version 0.2.4.
